### ISSUE TITLE
CORS

### ISSUE THREAD

**Issue by felipebastos** [bcc-dw-20212/AgendaBack#1]
Conforme expliquei em sala, se o frontend for servido em outro processo, teremos erro de CORS. A API vai recusar as requisições do mesmo. Há duas opções:
- [Django-CORS-Headers](https://pypi.org/project/django-cors-headers/): Essa lib permitirá executarem o frontend noutro serviço ou até noutra máquina e o backend aceitar as requisições
- Dar build no projeto do frontend e servir os arquivos de forma estática. Nesse [post](https://medium.com/swlh/django-angular-4-a-powerful-web-application-60b6fb39ef34) do Medium tem uma excelente sequência que pode servir mesmo no caso do projeto em React.

**Comment by maoubuda** [comment]
> Conforme expliquei em sala, se o frontend for servido em outro processo, teremos erro de CORS. A API vai recusar as requisições do mesmo. Há duas opções:
> 
> * [Django-CORS-Headers](https://pypi.org/project/django-cors-headers/): Essa lib permitirá executarem o frontend noutro serviço ou até noutra máquina e o backend aceitar as requisições
> * Dar build no projeto do frontend e servir os arquivos de forma estática. Nesse [post](https://medium.com/swlh/django-angular-4-a-powerful-web-application-60b6fb39ef34) do Medium tem uma excelente sequência que pode servir mesmo no caso do projeto em React.

A lib do cors, é só instalar?

**Comment by felipebastos** [comment]
> > Conforme expliquei em sala, se o frontend for servido em outro processo, teremos erro de CORS. A API vai recusar as requisições do mesmo. Há duas opções:
> > 
> > * [Django-CORS-Headers](https://pypi.org/project/django-cors-headers/): Essa lib permitirá executarem o frontend noutro serviço ou até noutra máquina e o backend aceitar as requisições
> > * Dar build no projeto do frontend e servir os arquivos de forma estática. Nesse [post](https://medium.com/swlh/django-angular-4-a-powerful-web-application-60b6fb39ef34) do Medium tem uma excelente sequência que pode servir mesmo no caso do projeto em React.
> 
> A lib do cors, é só instalar?

Sim, e fazer a configuração basica de INSTALLED_APPS, do MIDDLEWARE pra ativar no projeto. Também CORS_ALLOWED_ORIGINS, pra simplificar pode ser pra *

Isso tudo é no arquivo settings.py do projeto.

**Comment by maoubuda** [comment]
> Conforme expliquei em sala, se o frontend for servido em outro processo, teremos erro de CORS. A API vai recusar as requisições do mesmo. Há duas opções:
> 
> * [Django-CORS-Headers](https://pypi.org/project/django-cors-headers/): Essa lib permitirá executarem o frontend noutro serviço ou até noutra máquina e o backend aceitar as requisições
> * Dar build no projeto do frontend e servir os arquivos de forma estática. Nesse [post](https://medium.com/swlh/django-angular-4-a-powerful-web-application-60b6fb39ef34) do Medium tem uma excelente sequência que pode servir mesmo no caso do projeto em React.

CORS Solved!
